{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "from nipype.interfaces.io import DataSink, SelectFiles, DataGrabber \n",
    "from nipype.interfaces.utility import IdentityInterface, Function    \n",
    "from nipype.pipeline.engine import Node, Workflow, JoinNode, MapNode\n",
    "from nipype.interfaces import fsl\n",
    "from nipype import config, logging\n",
    "from datetime import date\n",
    "from pandas import Series, read_csv, to_numeric\n",
    "from os import getcwd\n",
    "from os.path import join, expanduser"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Set variables\n",
    "user = expanduser('~')\n",
    "\n",
    "#Set user for laptop\n",
    "if user == '/Users/lucindasisk':\n",
    "    base = '/Users/lucindasisk/Desktop/Milgram/candlab'\n",
    "    home = join(base,'analyses/shapes/dwi')\n",
    "    data_dir = join(base, 'analyses/shapes/dwi/eddyCUDA_data')\n",
    "    workflow_dir = join(base, 'analyses/shapes/dwi/eddyCUDA_workflow')\n",
    "    raw_dir = join(base, 'data/mri/bids_recon/shapes')\n",
    "\n",
    "#Set user for Grace\n",
    "if user == '/home/fas/gee_dylan/lms233':\n",
    "    home = getcwd() + '/..'\n",
    "    data_dir = join(home, 'eddyCUDA_data')\n",
    "    workflow_dir = join(home, 'eddyCUDA_workflow')\n",
    "\n",
    "#Set user for Milgram\n",
    "if user == '/home/lms233':\n",
    "    home = '/gpfs/milgram/project/gee_dylan/candlab'\n",
    "    data_dir = 'analyses/shapes/dwi/data'\n",
    "    workflow_dir = join(home, 'analyses/shapes/dwi/workflows')\n",
    "    raw_dir = join(home, 'data/mri/bids_recon/shapes')\n",
    "    \n",
    "# Manual subject list\n",
    "#subject_list = ['sub-A200', 'sub-A201', 'sub-A687', 'sub-A694', 'sub-A695', 'sub-A698']  # , 'sub-A201']\n",
    "    \n",
    "# Read in subject subject_list\n",
    "subject_csv = read_csv(home + '/scripts/shapes/mri/dwi/shapes_dwi_subjList_08.07.2019.txt', sep=' ', header=None)\n",
    "subject_list = subject_csv[0].values.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup Datasink, Infosource, Selectfiles\n",
    "\n",
    "datasink = Node(DataSink(base_directory=data_dir,\n",
    "                         substitutions=[('_subject_id_', '')]),\n",
    "                name='datasink')\n",
    "\n",
    "# Set infosource iterables\n",
    "infosource = Node(IdentityInterface(fields=['subject_id']),\n",
    "                  name=\"infosource\")\n",
    "infosource.iterables = [('subject_id', subject_list)]\n",
    "\n",
    "# SelectFiles\n",
    "template = dict(mask=join(home, 'analyses/shapes/dwi/data/2_Preprocessed/{subject_id}/{subject_id}_ses-shapesV1_T1w_flirt_brain_mask.nii.gz'),\n",
    "                dti=join(\n",
    "                    home, 'analyses/shapes/dwi/data/2_Preprocessed/{subject_id}/preprocessed_dwi.nii.gz'),\n",
    "                bval=join(\n",
    "                    raw_dir, '{subject_id}/ses-shapesV1/dwi/{subject_id}_ses-shapesV1_dwi.bval'),\n",
    "                bvec=join(\n",
    "                    raw_dir, '{subject_id}/ses-shapesV1/dwi/{subject_id}_ses-shapesV1_dwi.bvec'),\n",
    "                aps=join(home, 'analyses/shapes/dwi/shapes_acqparams.txt'),\n",
    "                index=join(home, 'analyses/shapes/dwi/shapes_index.txt')    \n",
    "                )\n",
    "\n",
    "\n",
    "sf = Node(SelectFiles(template,\n",
    "                      base_directory=home),\n",
    "          name='sf')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Eddy_CUDA Node\n",
    "# FSL Eddy correction to remove eddy current distortion\n",
    "\n",
    "eddy = Node(fsl.Eddy(is_shelled=True,\n",
    "                     interp='trilinear',\n",
    "                     method='jac',\n",
    "                     output_type='NIFTI_GZ',\n",
    "                     residuals=True,\n",
    "                     use_cuda=True,\n",
    "                     cnr_maps=True,\n",
    "                     repol=True),\n",
    "            name='eddy')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/usr/local/anaconda3/lib/python3.6/site-packages/nipype/utils/misc.py:367: UserWarning: Current folder does not exist, replacing with \"/Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion\" instead.\n",
      "  warn('Current folder does not exist, replacing with \"%s\" instead.' % cwd)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "190812-13:49:09,497 nipype.workflow INFO:\n",
      "\t Generated workflow graph: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/graph.png (graph2use=flat, simple_form=True).\n",
      "190812-13:49:09,512 nipype.workflow INFO:\n",
      "\t Workflow eddy_flow settings: ['check', 'execution', 'logging', 'monitoring']\n",
      "190812-13:49:09,888 nipype.workflow INFO:\n",
      "\t Running in parallel.\n",
      "190812-13:49:09,893 nipype.workflow INFO:\n",
      "\t [MultiProc] Running 0 tasks, and 6 jobs ready. Free memory (GB): 28.80/28.80, Free processors: 4/4.\n",
      "190812-13:49:09,966 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:09,987 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddy_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A698/sf\".\n",
      "190812-13:49:10,4 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,22 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,30 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddy_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A695/sf\".\n",
      "190812-13:49:10,51 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,64 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,69 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddy_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A694/sf\".\n",
      "190812-13:49:10,89 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,108 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,112 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddy_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A687/sf\".\n",
      "190812-13:49:10,129 nipype.workflow INFO:\n",
      "\t [Node] Outdated cache found for \"eddy_flow.sf\".\n",
      "190812-13:49:10,357 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:49:10,429 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:49:10,444 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:49:10,448 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddy_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A698/sf)\n",
      "190812-13:49:10,486 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:49:10,502 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddy_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A695/sf)\n",
      "190812-13:49:10,516 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddy_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A694/sf)\n",
      "190812-13:49:10,559 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddy_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddy_flow/_subject_id_sub-A687/sf)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Process Process-43:\n",
      "Process Process-42:\n",
      "Process Process-41:\n",
      "Process Process-44:\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 258, in _bootstrap\n",
      "    self.run()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/concurrent/futures/process.py\", line 169, in _process_worker\n",
      "    call_item = call_queue.get(block=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/concurrent/futures/process.py\", line 169, in _process_worker\n",
      "    call_item = call_queue.get(block=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/concurrent/futures/process.py\", line 169, in _process_worker\n",
      "    call_item = call_queue.get(block=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py\", line 93, in run\n",
      "    self._target(*self._args, **self._kwargs)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/queues.py\", line 93, in get\n",
      "    with self._rlock:\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/queues.py\", line 93, in get\n",
      "    with self._rlock:\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/queues.py\", line 93, in get\n",
      "    with self._rlock:\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/concurrent/futures/process.py\", line 169, in _process_worker\n",
      "    call_item = call_queue.get(block=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/synchronize.py\", line 96, in __enter__\n",
      "    return self._semlock.__enter__()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/synchronize.py\", line 96, in __enter__\n",
      "    return self._semlock.__enter__()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/synchronize.py\", line 96, in __enter__\n",
      "    return self._semlock.__enter__()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/queues.py\", line 94, in get\n",
      "    res = self._recv_bytes()\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "KeyboardInterrupt\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/connection.py\", line 216, in recv_bytes\n",
      "    buf = self._recv_bytes(maxlength)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/multiprocessing/connection.py\", line 407, in _recv_bytes\n",
      "    buf = self._recv(4)\n"
     ]
    },
    {
     "ename": "KeyboardInterrupt",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-39-dff945de1006>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     26\u001b[0m \u001b[0meddy_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbase_dir\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mworkflow_dir\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     27\u001b[0m \u001b[0meddy_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgraph2use\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'flat'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 28\u001b[0;31m \u001b[0meddy\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0meddy_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'MultiProc'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mplugin_args\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m'n_procs'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, plugin, plugin_args, updatehash)\u001b[0m\n\u001b[1;32m    597\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mstr2bool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'execution'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'create_report'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    598\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_write_report_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbase_dir\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexecgraph\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 599\u001b[0;31m         \u001b[0mrunner\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexecgraph\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mupdatehash\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mupdatehash\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    600\u001b[0m         \u001b[0mdatestr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutcnow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstrftime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'%Y%m%dT%H%M%S'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    601\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mstr2bool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'execution'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'write_provenance'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, graph, config, updatehash)\u001b[0m\n\u001b[1;32m    186\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    187\u001b[0m             \u001b[0msleep_til\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mloop_start\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0mpoll_sleep_secs\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 188\u001b[0;31m             \u001b[0msleep\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmax\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m0\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msleep_til\u001b[0m \u001b[0;34m-\u001b[0m \u001b[0mtime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    189\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    190\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_remove_node_dirs\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mKeyboardInterrupt\u001b[0m: "
     ]
    }
   ],
   "source": [
    "eddy_flow = Workflow(name='eddy_flow')\n",
    "eddy_flow.connect([(infosource, sf, [('subject_id', 'subject_id')]),\n",
    "                   (sf, eddy, [('dti', 'in_file'),\n",
    "                               ('bval', 'in_bval'),\n",
    "                               ('bvec', 'in_bvec'),\n",
    "                               ('index', 'in_index'),\n",
    "                               ('aps', 'in_acqp'),\n",
    "                               ('mask', 'in_mask')]),\n",
    "                   (eddy, datasink, [('out_corrected', '2_Preprocessed'),\n",
    "                                     ('out_rotated_bvecs', '2_Preprocessed.@par'),\n",
    "                                     ('out_movement_rms',\n",
    "                                      '2_Preprocessed.@par.@par'),\n",
    "                                     ('out_parameter',\n",
    "                                      '2_Preprocessed.@par.@par.@par'),\n",
    "                                     ('out_restricted_movement_rms',\n",
    "                                      '2_Preprocessed.@par.@par.@par.@par'),\n",
    "                                     ('out_shell_alignment_parameters',\n",
    "                                      '2_Preprocessed.@par.@par.@par.@par.@par'),\n",
    "                                     ('out_cnr_maps',\n",
    "                                      '2_Preprocessed.@par.@par.@par.@par.@par.@par'),\n",
    "                                     ('out_residuals',\n",
    "                                      '2_Preprocessed.@par.@par.@par.@par.@par.@par.@par'),\n",
    "                                     ('out_outlier_report',\n",
    "                                      '2_Preprocessed.@par.@par.@par.@par.@par.@par.@par.@par')])\n",
    "                   ])\n",
    "eddy_flow.base_dir = workflow_dir\n",
    "eddy_flow.write_graph(graph2use='flat')\n",
    "eddy = eddy_flow.run('MultiProc', plugin_args={'n_procs': 4})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [],
   "source": [
    "#eddyqc nodes\n",
    "\n",
    "# eddyquad = Node(fsl.EddyQuad(),     \n",
    "#                name='eddyquad')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "190812-13:53:45,239 nipype.workflow INFO:\n",
      "\t Generated workflow graph: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/graph.png (graph2use=flat, simple_form=True).\n",
      "190812-13:53:45,252 nipype.workflow INFO:\n",
      "\t Workflow eddyqc_flow settings: ['check', 'execution', 'logging', 'monitoring']\n",
      "190812-13:53:45,505 nipype.workflow INFO:\n",
      "\t Running in parallel.\n",
      "190812-13:53:45,508 nipype.workflow INFO:\n",
      "\t [MultiProc] Running 0 tasks, and 6 jobs ready. Free memory (GB): 28.80/28.80, Free processors: 4/4.\n",
      "190812-13:53:45,588 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A698/sf\".\n",
      "190812-13:53:45,621 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A695/sf\".\n",
      "190812-13:53:45,652 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A694/sf\".\n",
      "190812-13:53:45,686 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A687/sf\".\n",
      "190812-13:53:45,915 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:53:45,946 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:53:45,999 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A698/sf)\n",
      "190812-13:53:46,34 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A695/sf)190812-13:53:46,35 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "\n",
      "190812-13:53:46,39 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:53:46,113 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A694/sf)190812-13:53:46,112 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A687/sf)\n",
      "\n",
      "190812-13:53:47,537 nipype.workflow ERROR:\n",
      "\t Node sf.a5 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:47,539 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a5-1049d527-5f03-4fd0-b419-03b84dcb9f93.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A698/eddy_corrected\n",
      "\n",
      "190812-13:53:47,588 nipype.workflow ERROR:\n",
      "\t Node sf.a4 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:47,589 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a4-52972aca-5ef3-4968-9a6f-9f54c688ba39.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A695/eddy_corrected\n",
      "\n",
      "190812-13:53:47,635 nipype.workflow ERROR:\n",
      "\t Node sf.a3 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:47,636 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a3-b6ff0b17-f212-46db-8665-6b8a4ec50ff4.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A694/eddy_corrected\n",
      "\n",
      "190812-13:53:47,686 nipype.workflow ERROR:\n",
      "\t Node sf.a2 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:47,687 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a2-11251794-af0f-42a9-89a1-212643fea4cd.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A687/eddy_corrected\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "190812-13:53:47,711 nipype.workflow INFO:\n",
      "\t [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 28.80/28.80, Free processors: 4/4.\n",
      "190812-13:53:47,781 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A201/sf\".\n",
      "190812-13:53:47,820 nipype.workflow INFO:\n",
      "\t [Node] Setting-up \"eddyqc_flow.sf\" in \"/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A200/sf\".\n",
      "190812-13:53:48,97 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:53:48,113 nipype.workflow INFO:\n",
      "\t [Node] Running \"sf\" (\"nipype.interfaces.io.SelectFiles\")\n",
      "190812-13:53:48,159 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A201/sf)\n",
      "190812-13:53:48,179 nipype.workflow WARNING:\n",
      "\t [Node] Error on \"eddyqc_flow.sf\" (/Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_workflow/eddyqc_flow/_subject_id_sub-A200/sf)\n",
      "190812-13:53:49,535 nipype.workflow ERROR:\n",
      "\t Node sf.a1 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:49,536 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135349-lucindasisk-sf.a1-97376276-4125-4dd3-8970-68dbc1996c6b.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A201/eddy_corrected\n",
      "\n",
      "190812-13:53:49,584 nipype.workflow ERROR:\n",
      "\t Node sf.a0 failed to run on host Lucindas-MBP.wireless.yale.internal.\n",
      "190812-13:53:49,585 nipype.workflow ERROR:\n",
      "\t Saving crash info to /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135349-lucindasisk-sf.a0-eb72e348-c811-4b2c-86c9-1812dade9c7c.pklz\n",
      "Traceback (most recent call last):\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py\", line 69, in run_node\n",
      "    result['result'] = node.run(updatehash=updatehash)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 472, in run\n",
      "    result = self._run_interface(execute=True)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 563, in _run_interface\n",
      "    return self._run_command(execute)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py\", line 643, in _run_command\n",
      "    result = self._interface.run(cwd=outdir)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 377, in run\n",
      "    outputs = self.aggregate_outputs(runtime)\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/base/core.py\", line 455, in aggregate_outputs\n",
      "    predicted_outputs = self._list_outputs()\n",
      "  File \"/usr/local/anaconda3/lib/python3.6/site-packages/nipype/interfaces/io.py\", line 1412, in _list_outputs\n",
      "    raise IOError(msg)\n",
      "OSError: No files were found matching eddy_base template: /Users/lucindasisk/Desktop/Milgram/candlab/analyses/shapes/dwi/eddyCUDA_data/3_Eddy_Corrected/sub-A200/eddy_corrected\n",
      "\n",
      "190812-13:53:49,608 nipype.workflow INFO:\n",
      "\t [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 28.80/28.80, Free processors: 4/4.\n",
      "190812-13:53:51,512 nipype.workflow INFO:\n",
      "\t ***********************************\n",
      "190812-13:53:51,513 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a5\n",
      "190812-13:53:51,514 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a5-1049d527-5f03-4fd0-b419-03b84dcb9f93.pklz\n",
      "190812-13:53:51,514 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a4\n",
      "190812-13:53:51,515 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a4-52972aca-5ef3-4968-9a6f-9f54c688ba39.pklz\n",
      "190812-13:53:51,515 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a3\n",
      "190812-13:53:51,516 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a3-b6ff0b17-f212-46db-8665-6b8a4ec50ff4.pklz\n",
      "190812-13:53:51,516 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a2\n",
      "190812-13:53:51,517 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135347-lucindasisk-sf.a2-11251794-af0f-42a9-89a1-212643fea4cd.pklz\n",
      "190812-13:53:51,517 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a1\n",
      "190812-13:53:51,518 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135349-lucindasisk-sf.a1-97376276-4125-4dd3-8970-68dbc1996c6b.pklz\n",
      "190812-13:53:51,519 nipype.workflow ERROR:\n",
      "\t could not run node: eddyqc_flow.sf.a0\n",
      "190812-13:53:51,519 nipype.workflow INFO:\n",
      "\t crashfile: /Users/lucindasisk/Desktop/Milgram/candlab/scripts/shapes/mri/dwi/Diffusion/crash-20190812-135349-lucindasisk-sf.a0-eb72e348-c811-4b2c-86c9-1812dade9c7c.pklz\n",
      "190812-13:53:51,520 nipype.workflow INFO:\n",
      "\t ***********************************\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Workflow did not execute cleanly. Check log for details",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-56-960c9872da7b>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m     12\u001b[0m \u001b[0meddyqc_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbase_dir\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mworkflow_dir\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     13\u001b[0m \u001b[0meddyqc_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwrite_graph\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mgraph2use\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'flat'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 14\u001b[0;31m \u001b[0meddyqc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0meddyqc_flow\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'MultiProc'\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mplugin_args\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m'n_procs'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;36m4\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, plugin, plugin_args, updatehash)\u001b[0m\n\u001b[1;32m    597\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mstr2bool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'execution'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'create_report'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    598\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_write_report_info\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbase_dir\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mname\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mexecgraph\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 599\u001b[0;31m         \u001b[0mrunner\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrun\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mexecgraph\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mupdatehash\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mupdatehash\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconfig\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    600\u001b[0m         \u001b[0mdatestr\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mdatetime\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mutcnow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mstrftime\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m'%Y%m%dT%H%M%S'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    601\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mstr2bool\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'execution'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'write_provenance'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py\u001b[0m in \u001b[0;36mrun\u001b[0;34m(self, graph, config, updatehash)\u001b[0m\n\u001b[1;32m    189\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    190\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_remove_node_dirs\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 191\u001b[0;31m         \u001b[0mreport_nodes_not_run\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnotrun\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    192\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    193\u001b[0m         \u001b[0;31m# close any open resources\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/usr/local/anaconda3/lib/python3.6/site-packages/nipype/pipeline/plugins/tools.py\u001b[0m in \u001b[0;36mreport_nodes_not_run\u001b[0;34m(notrun)\u001b[0m\n\u001b[1;32m     80\u001b[0m                 \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdebug\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msubnode\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_id\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     81\u001b[0m         \u001b[0mlogger\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0minfo\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"***********************************\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 82\u001b[0;31m         raise RuntimeError(('Workflow did not execute cleanly. '\n\u001b[0m\u001b[1;32m     83\u001b[0m                             'Check log for details'))\n\u001b[1;32m     84\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Workflow did not execute cleanly. Check log for details"
     ]
    }
   ],
   "source": [
    "# Workflow\n",
    "\n",
    "# eddyqc_flow = Workflow(name='eddyqc_flow')\n",
    "# eddyqc_flow.connect([(infosource, sf, [('subject_id', 'subject_id')]),\n",
    "#                      (sf, eddyquad, [('eddy_base','base_name'),\n",
    "#                                      ('index', 'idx_file'),\n",
    "#                                      ('aps', 'param_file'),\n",
    "#                                      ('mask', 'mask_file'),\n",
    "#                                      ('bval', 'bval_file'),\n",
    "#                                      ('bvec','bvec_file')])\n",
    "#                    ])\n",
    "# eddyqc_flow.base_dir = workflow_dir\n",
    "# eddyqc_flow.write_graph(graph2use='flat')\n",
    "# eddyqc = eddyqc_flow.run('MultiProc', plugin_args={'n_procs': 4})\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
